# Generated by Django 2.2.26 on 2022-03-06 16:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Society',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('societyName', models.CharField(max_length=64, unique=True)),
                ('logo', models.ImageField(upload_to='')),
                ('description', models.CharField(max_length=256)),
                ('views', models.IntegerField(default=0)),
                ('members', models.IntegerField(default=0)),
            ],
            options={
                'verbose_name_plural': 'Societies',
            },
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('eventName', models.CharField(max_length=64)),
                ('description', models.CharField(max_length=256)),
                ('members', models.IntegerField(default=0)),
                ('societyName', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rango.Society')),
            ],
        ),
    ]
