# Generated by Django 2.2.26 on 2022-03-28 05:20

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('rango', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='date',
            field=models.DateField(default=datetime.datetime(2022, 3, 28, 5, 20, 45, 675076, tzinfo=utc)),
        ),
    ]
