# Generated by Django 2.2.26 on 2022-03-15 17:18

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rango', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='event',
            old_name='societyName',
            new_name='society',
        ),
        migrations.AlterField(
            model_name='event',
            name='date',
            field=models.DateField(default=datetime.date(2022, 3, 15)),
        ),
    ]
