# Generated by Django 2.2.26 on 2022-03-12 17:42

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('rango', '0003_auto_20220307_1759'),
    ]

    operations = [
        migrations.RenameField(
            model_name='event',
            old_name='members',
            new_name='memberNum',
        ),
        migrations.RenameField(
            model_name='society',
            old_name='members',
            new_name='memberNum',
        ),
        migrations.AddField(
            model_name='event',
            name='attendee',
            field=models.ManyToManyField(to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='society',
            name='member',
            field=models.ManyToManyField(related_name='memberOf', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='society',
            name='owner',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='is_student',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='event',
            name='date',
            field=models.DateField(default=datetime.date(2022, 3, 12)),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='is_society',
            field=models.BooleanField(default=False),
        ),
    ]
